const data = {
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt", //slug is the url friendly naame of a product
      category: "Shirt",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      decription: "A popular Shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirt",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Coke",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      decription: "A classy fitted shirt",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirt",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      countInStock: 20,
      decription: "A popular slim Shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "ajibadde",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      decription: "Smart looking pants",
    },
    {
      name: "Jean Pant",
      slug: "jean-pant",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 74,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      decription: "A popular pant for everybody",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Shirt",
      image: "/images/pants3.jpg",
      price: 70,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      decription: "A popular Zara pants",
    },
  ],
};

export default data;
